version: '3.8'

networks:
  inception:
    name: inception

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/www/html
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/debian/volumes/db_data
      o: bind
      
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/debian/volumes/wordpress_files
      o: bind